name: proyecto_dbt
version: '1.0'
config-version: 2

profile: default

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  proyecto_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table
